<a href="https://colab.research.google.com/github/farahelnakhal/applied_data_science/blob/main/pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Order of the Muggle Magic Science

In the year 2020, Professor Minerva McGonagall, headmaster of the Hogwarts School of Witchcraft and Wizardry, heard rumours of a new magic **science** being learnt by muggles (or ordinary human beings). This unknown and dark science, being called **data science** in the muggle community, could pose serious threat to Hogwarts. Professor McGonagall does not want to take any chances shall that happen.

Starting of the year 2021, she, thus, decided to create an **Order of the Muggle Magic Science**, an army of Hogwarts students proficient in the "magical art of data science" course.

It is now the end of the spring term of 2021, and the first class of experts is ready to join the Ministry of Magic. Competition is fierce: out of the 24 students enrolled in the class, only the students who achieve greater than or equal to an **A- grade** in the course, and **attended ALL the 28 classes** shall join the Ministry. There's just one small task left -- that of assigning grades to students. Professor McGonagall has generously outsourced this task to a trusted muggle community at NYUAD in exchange for 120 magical points.

*True Story..*

The magical art of data science course had **10 assignments**, with each assignment worth **120 points**; **10 recitations**, with each recitation worth **50 points**; **28 points for class attendance and participation**, **1 point** for each class; and **100 points for the final class project**.

Each assignment was **6%** of the grade.

Each recitation was **1%** of the grade.

Class attendance was **5%** of the grade.

Project was worth **25%** of the grade.

The overall distribution of points and percentages was as follows:

| Activity  | Points  | Grade Percentage  |
|---|---|---|
|Class Participation   |  28 points  | 5%  |
| Recitation / Lab Participation  | 500 points | 10%  |
| Ten Highest Problem Sets  | 1200 points  | 60%   |
| Final Project  | 100 points  |  25%  |

Course was not curved, and the final percentages are to be converted according to the following rubric:

|  A | A-  | B+  | B  | B-  | C+  | C  | C-  | D  |  F |
|---|---|---|---|---|---|---|---|---|---|
| [95-100]%  | [90-94]%  | [85-89]%  | [80-84]%  | [75-79]%  | [70-74]%  | [65-69]%  | [60-64]%  | [50-59]%  | [0-49]% |


Anyhow, Professor McGonaggal has provided us with a csv file with the grades of students for each of the assignments, recitations, class attendance and project. In this homework and following tasks, you will use that file to compute the final grades of students.

## Part I: CSV to Pandas

Load the csv file, *muggle_science_grades.csv* attached with this notebook as a pandas dataframe, and print the head of the file.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

import pandas as pd #import pandas library

path = '/content/drive/MyDrive/applied_data_science/datasets' #path to dataset file
df = pd.read_csv(path +'/muggle_science_grades.csv') #read csv

df #display dataframe

,Student,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,R3,R4,R5,R6,R7,R8,R9,R10,Class Attendance,Project
0,Albus Severus Potter,111,119,80,118,102,111,116,116,118,...,27,48,40,49,47,31,36,18,27,93
1,Rose Granger-Weasley,117,110,92,115,103,118,106,120,115,...,10,48,45,48,50,49,12,24,27,100
2,Scorpius Malfoy,106,112,97,111,118,114,107,101,105,...,14,43,50,50,43,38,32,29,27,96
3,Delphi (Delphini) Diggory,111,111,91,110,113,110,120,114,102,...,20,45,42,47,48,36,37,36,28,96
4,Yann Fredericks,115,100,95,117,114,114,110,107,106,...,28,45,42,41,48,34,24,30,27,90
5,Craig Bowker Jr,109,109,113,103,103,112,110,108,110,...,47,44,42,49,41,42,20,24,28,94
6,Karl Jenkins,113,109,109,103,114,115,100,116,101,...,39,49,48,46,40,35,13,16,28,91
7,Polly Chapman,108,115,104,119,105,118,111,100,102,...,19,49,45,41,43,30,40,39,27,96
8,Lily Luna Potter,104,108,116,120,117,111,118,112,105,...,15,49,44,40,48,42,46,32,27,92
9,James Sirius Potter,108,104,99,115,111,118,107,108,103,...,47,45,45,41,46,32,28,13,27,95
10,Hugo Weasley,100,119,115,114,104,114,113,107,110,...,45,41,46,49,46,37,47,18,27,90
11,Victoire Weasley,114,103,110,105,107,116,112,116,119,...,25,43,50,50,48,35,28,47,28,92
12,Lorcan Scamander,105,107,90,105,120,119,102,106,105,...,50,46,44,46,49,42,12,16,28,92
13,Lysander Scamander,112,110,119,119,111,114,108,113,112,...,17,46,48,43,49,47,43,49,27,92
14,Araminta Malfoy,108,120,100,106,105,113,117,107,118,...,47,50,48,45,49,42,30,15,28,96
15,Frank Longbottom,117,107,107,107,117,111,101,107,112,...,17,44,41,41,43,32,19,50,27,98
16,Mason Wood,119,106,88,105,118,114,102,120,117,...,37,48,45,40,49,33,33,34,28,95
17,Jessica Finnigan,115,114,102,114,113,114,116,103,115,...,43,43,47,47,47,30,50,22,27,92
18,Freya Parkinson,108,109,106,107,106,114,118,111,103,...,46,48,42,46,42,41,23,16,28,100
19,Kimberly Wood,119,120,103,105,103,112,102,108,109,...,37,48,40,45,41,37,48,15,28,94
20,Alice Longbottom,119,118,117,104,114,113,115,111,103,...,12,49,41,43,42,40,41,28,27,96
21,Grace Longbottom,102,107,102,120,117,111,106,112,108,...,13,48,49,49,46,32,26,18,27,94
22,Teddy Lupin,112,107,89,103,120,117,110,115,107,...,16,49,43,50,44,39,48,38,27,92
23,Roxanne Rachelle Weasley,108,115,82,115,113,114,120,117,117,...,13,43,49,40,46,35,33,31,27,92

## Part II: Retrieving Selected Columns

From the dataset you just read from the csv file as a DataFrame, retrieve only the columns that represent grades for problem sets (i.e. *P1, P2, P3, ... P10*)

In [ ]:
df.filter(regex="^P[0-9]+$") #filter using regex

#^: start of string (no characters before)
#P: the prefix for PS cols
#[0-9]: one or more digits (0 through 9)
#$: end of string (no characters after)

     P1   P2   P3   P4   P5   P6   P7   P8   P9  P10
0   111  119   80  118  102  111  116  116  118  104
1   117  110   92  115  103  118  106  120  115  117
2   106  112   97  111  118  114  107  101  105  118
3   111  111   91  110  113  110  120  114  102  119
4   115  100   95  117  114  114  110  107  106  118
5   109  109  113  103  103  112  110  108  110  107
6   113  109  109  103  114  115  100  116  101  103
7   108  115  104  119  105  118  111  100  102  102
8   104  108  116  120  117  111  118  112  105  112
9   108  104   99  115  111  118  107  108  103  120
10  100  119  115  114  104  114  113  107  110  105
11  114  103  110  105  107  116  112  116  119  109
12  105  107   90  105  120  119  102  106  105  102
13  112  110  119  119  111  114  108  113  112  105
14  108  120  100  106  105  113  117  107  118  114
15  117  107  107  107  117  111  101  107  112  110
16  119  106   88  105  118  114  102  120  117  111
17  115  114  102  114  113  114  116  103  115  101
18  108  109  106  107  106  114  118  111  103  109
19  119  120  103  105  103  112  102  108  109  111
20  119  118  117  104  114  113  115  111  103  120
21  102  107  102  120  117  111  106  112  108  118
22  112  107   89  103  120  117  110  115  107  103
23  108  115   82  115  113  114  120  117  117  114

## Part III: Adding New Columns

Based on the rubric above, we want you to add a new column to the DataFrame called *Overall Percentage* which represents the overall percentage a student has achieved in the course based on the rubric given above.

In [ ]:
#takes appropriate cols, divides by max number of points and multiplies by percentage of final grade, then by 100 to turn to percentage
sum = (((df["Class Attendance"] / 28) * 0.05) + ((df.filter(regex="^P[0-9]+$").sum(axis=1) / 1200) * 0.6) + ((df.filter(regex="^R[0-9]+$").sum(axis=1) / 500) * 0.1) + ((df["Project"] / 100) * 0.25)) * 100

df["Overall Percentage"] = sum #assigns sum to new col
df

,Student,P1,P2,P3,P4,P5,P6,P7,P8,P9,...,R4,R5,R6,R7,R8,R9,R10,Class Attendance,Project,Overall Percentage
0,Albus Severus Potter,111,119,80,118,102,111,116,116,118,...,48,40,49,47,31,36,18,27,93,90.541429
1,Rose Granger-Weasley,117,110,92,115,103,118,106,120,115,...,48,45,48,50,49,12,24,27,100,92.931429
2,Scorpius Malfoy,106,112,97,111,118,114,107,101,105,...,43,50,50,43,38,32,29,27,96,90.951429
3,Delphi (Delphini) Diggory,111,111,91,110,113,110,120,114,102,...,45,42,47,48,36,37,36,28,96,92.210000
4,Yann Fredericks,115,100,95,117,114,114,110,107,106,...,45,42,41,48,34,24,30,27,90,89.761429
5,Craig Bowker Jr,109,109,113,103,103,112,110,108,110,...,44,42,49,41,42,20,24,28,94,90.760000
6,Karl Jenkins,113,109,109,103,114,115,100,116,101,...,49,48,46,40,35,13,16,28,91,89.420000
7,Polly Chapman,108,115,104,119,105,118,111,100,102,...,49,45,41,43,30,40,39,27,96,91.061429
8,Lily Luna Potter,104,108,116,120,117,111,118,112,105,...,49,44,40,48,42,46,32,27,92,92.071429
9,James Sirius Potter,108,104,99,115,111,118,107,108,103,...,45,45,41,46,32,28,13,27,95,90.881429
10,Hugo Weasley,100,119,115,114,104,114,113,107,110,...,41,46,49,46,37,47,18,27,90,90.651429
11,Victoire Weasley,114,103,110,105,107,116,112,116,119,...,43,50,50,48,35,28,47,28,92,91.770000
12,Lorcan Scamander,105,107,90,105,120,119,102,106,105,...,46,44,46,49,42,12,16,28,92,89.050000
13,Lysander Scamander,112,110,119,119,111,114,108,113,112,...,46,48,43,49,47,43,49,27,92,92.611429
14,Araminta Malfoy,108,120,100,106,105,113,117,107,118,...,50,48,45,49,42,30,15,28,96,92.760000
15,Frank Longbottom,117,107,107,107,117,111,101,107,112,...,44,41,41,43,32,19,50,27,98,91.641429
16,Mason Wood,119,106,88,105,118,114,102,120,117,...,48,45,40,49,33,33,34,28,95,92.010000
17,Jessica Finnigan,115,114,102,114,113,114,116,103,115,...,43,47,47,47,30,50,22,27,92,91.531429
18,Freya Parkinson,108,109,106,107,106,114,118,111,103,...,48,42,46,42,41,23,16,28,100,92.450000
19,Kimberly Wood,119,120,103,105,103,112,102,108,109,...,48,40,45,41,37,48,15,28,94,91.020000
20,Alice Longbottom,119,118,117,104,114,113,115,111,103,...,49,41,43,42,40,41,28,27,96,93.301429
21,Grace Longbottom,102,107,102,120,117,111,106,112,108,...,48,49,49,46,32,26,18,27,94,90.931429
22,Teddy Lupin,112,107,89,103,120,117,110,115,107,...,49,43,50,44,39,48,38,27,92,90.351429
23,Roxanne Rachelle Weasley,108,115,82,115,113,114,120,117,117,...,43,49,40,46,35,33,31,27,92,91.211429

## Part IV: Dropping Data

Now that you have computed the final percentages, we don't need other columns anymore. We would only like to keep the *Student*, *Class Attendance* and *Overall Percentage* column as we would use these columns to identify who qualifies to join the ministry. Write code to accomplish that below.

In [ ]:
#create new data frame with those 3 cols only
df = df[["Student", "Class Attendance", "Overall Percentage"]]
#alternative solution:
#df = df.drop(columns=df.filter(regex="^P[0-9]+$").columns.tolist() + df.filter(regex="^R[0-9]+$").columns.tolist() + ["Project"])
df

                      Student  Class Attendance  Overall Percentage
0        Albus Severus Potter                27           90.541429
1        Rose Granger-Weasley                27           92.931429
2             Scorpius Malfoy                27           90.951429
3   Delphi (Delphini) Diggory                28           92.210000
4             Yann Fredericks                27           89.761429
5             Craig Bowker Jr                28           90.760000
6                Karl Jenkins                28           89.420000
7               Polly Chapman                27           91.061429
8            Lily Luna Potter                27           92.071429
9         James Sirius Potter                27           90.881429
10               Hugo Weasley                27           90.651429
11           Victoire Weasley                28           91.770000
12           Lorcan Scamander                28           89.050000
13         Lysander Scamander                27           92.611429
14            Araminta Malfoy                28           92.760000
15           Frank Longbottom                27           91.641429
16                 Mason Wood                28           92.010000
17           Jessica Finnigan                27           91.531429
18            Freya Parkinson                28           92.450000
19              Kimberly Wood                28           91.020000
20           Alice Longbottom                27           93.301429
21           Grace Longbottom                27           90.931429
22                Teddy Lupin                27           90.351429
23   Roxanne Rachelle Weasley                27           91.211429

 ## Part V: Qualifiers for Ministry

Finally, using the thresholds and conditions given in the intro paragraph, print names of students who were qualified to work at the ministry i.e. students who have a grade that is equal to an **A- or above** AND have **attended ALL the 28 lectures**.

In [ ]:
#filter by attendance==28 and percentage >= 90
qualified_students = df[(df["Class Attendance"] == 28) & (df["Overall Percentage"] >= 90)]
qualified_students #display qualified students

                      Student  Class Attendance  Overall Percentage
3   Delphi (Delphini) Diggory                28               92.21
5             Craig Bowker Jr                28               90.76
11           Victoire Weasley                28               91.77
14            Araminta Malfoy                28               92.76
16                 Mason Wood                28               92.01
18            Freya Parkinson                28               92.45
19              Kimberly Wood                28               91.02